version: '2'

volumes:
  resin-data:
  supervisor-data:

services:
  supervisor:
    build: ./supervisor
    ports:
      - "80:9001"
    volumes:
      - "resin-data:/data"
      - "supervisor-data:/supervisor-data"
    labels:
      io.balena.features.balena-socket: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.procfs: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
      io.balena.update.strategy: download-then-kill
      io.balena.update.handover-timeout: ''
